# Generated by Django 6.0.3 on 2026-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
