# Generated by Django 6.0.3 on 2026-03-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_objetivoahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoahorro',
            name='monto_ahorrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
